# Generated by Django 4.2.6 on 2023-11-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
