# Generated by Django 4.2.6 on 2023-11-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_rename_created_at_processedphoto_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_name', models.CharField(max_length=255)),
                ('photo_image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedPhoto',
        ),
    ]
