# Generated by Django 4.2.6 on 2023-11-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_uploadedphoto_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='key_points/')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedPhoto',
        ),
    ]
