# Generated by Django 4.2.6 on 2023-11-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_keypoints_delete_uploadedphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyPoints',
        ),
    ]
