# Generated by Django 4.2.6 on 2023-11-05 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypoints',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='keypoints',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
