# Generated by Django 4.2.6 on 2023-11-06 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocks', '0013_alter_keypoints_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypoints',
            name='user',
        ),
        migrations.AddField(
            model_name='keypoints',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
