# Generated by Django 4.2.6 on 2023-11-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0015_remove_keypoints_uploaded_by_keypoints_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypoints',
            name='user',
        ),
    ]
