# Generated by Django 4.2.6 on 2023-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0017_keypoints_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(default='Processing', max_length=50)),
            ],
        ),
    ]
