# Generated by Django 4.2.6 on 2023-11-06 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocks', '0018_photoprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoprocess',
            name='user_id',
        ),
        migrations.AddField(
            model_name='photoprocess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
