# Generated by Django 4.2.6 on 2023-11-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0020_photoprocessisolation_keypointsisolation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoprocessisolation',
            name='user',
        ),
        migrations.DeleteModel(
            name='KeyPointsIsolation',
        ),
        migrations.DeleteModel(
            name='PhotoProcessIsolation',
        ),
    ]
