# Generated by Django 4.2.6 on 2023-11-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0022_keypoints_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoints',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
    ]
